# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 126084a4ff3aa76bd435a18c229e11aa2f218f359325ac6404680a70e4e7eb3c0e154e9eb52993de17d7eda0ba95fa1b3f86b694838e28cabf0ed0a8e69bbe15

test:
  secret_key_base: 7ee3e2690ec9fcd3750dcea654a1c855ff61719e3e48d98c6b3045636130c3c584638373c3c9dd64b6728ab74629930d854002a446eff1d4f56e31397de98e6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
